//=======================================================
//  This code is generated by Terasic System Builder
//  Modified: debug statements, heartbeat LED, correct adder
//=======================================================
//
// BUG FIXES APPLIED:
//   1. adder_test.c used 0xFF200000 (LW bridge) but LWH2F_Enable=false
//      in Qsys → that bridge is DISABLED → any access hangs the bus.
//      Correct base is 0xC0000000 (full H2F bridge).
//
//   2. pio64_out has no byteenable port. The HPS does 32-bit writes to
//      a 64-bit PIO. Each 32-bit write zeros the other half. So writing
//      A_LO=0x1000 then A_HI=0x0234 leaves pio_out={0x0234, 0x0000},
//      sum = 0x0234, not 0x1234.
//      FIX: use adder_a[31:0] + adder_b[31:0] (different PIO instances
//      — writes to one do not affect the other).
//
//   3. LED DEADBEEF trigger: changed to check adder_a_export[31:0]
//      directly (not sum_a) so the LED latch fires as soon as the HPS
//      writes 0xDEADBEEF, independent of adder_b value.
//
// DEBUG FEATURES ADDED:
//   LED[7]  : 1 Hz heartbeat — blinks even with no HPS interaction.
//             If this stops, the 50 MHz clock or FPGA is dead.
//   LED[6]  : pio_dirty — goes high when HPS writes a new value.
//   LED[5]  : DDR3 sequencer active (seq != 0).
//   LED[4]  : hps_fpga_reset_n — 1 when HPS is out of reset (running).
//   LED[3:0]: DEADBEEF latch — shows adder_b_export[3:0] after trigger.
//
//   Qsys address map (via mm_bridge_0, H2F base 0xC0000000):
//     0x00-0x0F  pio128_out_0  WRITE  128-bit (4 x 32-bit words)
//     0x10-0x17  pio64_in_0    READ   64-bit  (adder_sum_export)
//     0x18-0x1F  pio64_out_1   WRITE  64-bit  (adder_b_export)
//     0x20-0x27  pio64_out_0   WRITE  64-bit  (adder_a_export)
//
//   adder_sum_export (read at 0xC0000010/14 via devmem):
//   [31:0]  sum_a = adder_a_export[31:0] + adder_b_export[31:0]
//   [63:32] debug_word:
//     [63:56] = 0xDB  magic marker (read this to verify bridge alive)
//     [55]    = heartbeat (toggling = FPGA clock alive)
//     [54]    = hps_fpga_reset_n
//     [53]    = pio_dirty
//     [52]    = ddr3_written (latched: DDR3 has been written at least once)
//     [51:50] = seq state (0=idle, 1=writing_A, 2=writing_B)
//     [49:32] = 0 (reserved)
//
// devmem2 debug commands (run on board, bridges must be enabled):
//   Read sum:         ./devmem2 0xC0000010 w
//   Read debug word:  ./devmem2 0xC0000014 w
//   Write adder_a:    ./devmem2 0xC0000020 w w 0x1000
//   Write adder_b:    ./devmem2 0xC0000018 w w 0x0234
//   Write pio128[0]:  ./devmem2 0xC0000000 w w 0x42
//   Check DDR3:       ./devmem2 0x3FFF003C w
//=======================================================

module DE10_NANO_SoC_GHRD(

    //////////// CLOCK //////////
    input               FPGA_CLK1_50,
    input               FPGA_CLK2_50,
    input               FPGA_CLK3_50,

    //////////// HPS //////////
    output   [14: 0]    HPS_DDR3_ADDR,
    output   [ 2: 0]    HPS_DDR3_BA,
    output              HPS_DDR3_CAS_N,
    output              HPS_DDR3_CK_N,
    output              HPS_DDR3_CK_P,
    output              HPS_DDR3_CKE,
    output              HPS_DDR3_CS_N,
    output   [ 3: 0]    HPS_DDR3_DM,
    inout    [31: 0]    HPS_DDR3_DQ,
    inout    [ 3: 0]    HPS_DDR3_DQS_N,
    inout    [ 3: 0]    HPS_DDR3_DQS_P,
    output              HPS_DDR3_ODT,
    output              HPS_DDR3_RAS_N,
    output              HPS_DDR3_RESET_N,
    input               HPS_DDR3_RZQ,
    output              HPS_DDR3_WE_N,

    //////////// LED //////////
    output   [ 7: 0]    LED
);

//=======================================================
//  REG/WIRE declarations
//=======================================================
wire hps_fpga_reset_n;
wire        fpga_clk_50;
wire [63:0]  adder_a_export;      // PIO from HPS  (adder_a: operand written by HPS)
wire [63:0]  adder_b_export;      // PIO from HPS  (adder_b: operand written by HPS)
wire [63:0]  adder_sum_export;    // PIO to HPS    (read results + debug)
wire [127:0] pio128_out_export;   // 128-bit PIO from HPS (4 x 32-bit writable words)

assign fpga_clk_50 = FPGA_CLK1_50;

//=======================================================
//  DEBUG: 1 Hz heartbeat — tells you the FPGA is alive
//  At 50 MHz: toggle every 50_000_000 cycles → 2s period
//=======================================================
reg [25:0] heartbeat_cnt;
reg        heartbeat;

always @(posedge fpga_clk_50 or negedge hps_fpga_reset_n) begin
    if (!hps_fpga_reset_n) begin
        heartbeat_cnt <= 26'd0;
        heartbeat     <= 1'b0;
    end else begin
        if (heartbeat_cnt == 26'd49_999_999) begin
            heartbeat_cnt <= 26'd0;
            heartbeat     <= ~heartbeat;  // toggle every 1 second
        end else begin
            heartbeat_cnt <= heartbeat_cnt + 26'd1;
        end
    end
end

//=======================================================
//  Adder — uses two SEPARATE PIOs so 32-bit HPS writes
//  to one register do NOT corrupt the other.
//
//  Protocol (use devmem2 or adder_test):
//    Write operand 1 → adder_a at 0xC0000020  (low 32 bits)
//    Write operand 2 → adder_b at 0xC0000018  (low 32 bits)
//    Read  result    ← adder_sum at 0xC0000010 (sum_a in low 32)
//
//  WHY cross-PIO: pio64_out has no byteenable port, so a 32-bit
//  HPS write sets [31:0] and CLEARS [63:32] (or vice-versa).
//  Adding two halves of the SAME 64-bit PIO therefore fails.
//  Using one LOW-half from each of two separate PIOs avoids this.
//=======================================================
wire [31:0] sum_a = adder_a_export[31:0] + adder_b_export[31:0];

// sum_b: high halves (only useful if HPS writes A_HI / B_HI separately;
// those writes zero A_LO / B_LO respectively, so sum_a will change too).
// Kept for completeness but not exercised by the standard test.
wire [31:0] sum_b = adder_a_export[63:32] + adder_b_export[63:32];

//=======================================================
//  DEBUG: simulation $display statements
//  (stripped by synthesis; active only in Verilator/ModelSim)
//=======================================================
// synthesis translate_off
always @(posedge fpga_clk_50) begin
    if (adder_a_export !== 64'bx && adder_b_export !== 64'bx) begin
        $display("[ADDER] t=%0t  adder_a[31:0]=0x%08h  adder_b[31:0]=0x%08h  sum_a=0x%08h",
                 $time,
                 adder_a_export[31:0],
                 adder_b_export[31:0],
                 sum_a);
    end
end
// synthesis translate_on

//=======================================================
//  DEADBEEF → LED latch
//  Fires when HPS writes 0xDEADBEEF to adder_a (A_LO).
//  Latches adder_b_export[3:0] into LED[3:0].
//  LED[7:4] are always the debug indicators above.
//=======================================================
reg [3:0] led_latch;
always @(posedge fpga_clk_50 or negedge hps_fpga_reset_n) begin
    if (!hps_fpga_reset_n)
        led_latch <= 4'h0;
    else if (adder_a_export[31:0] == 32'hDEAD_BEEF)
        led_latch <= adder_b_export[3:0];
end

// synthesis translate_off
always @(posedge fpga_clk_50) begin
    if (adder_a_export[31:0] == 32'hDEAD_BEEF)
        $display("[LED] t=%0t  DEADBEEF trigger! latching adder_b[3:0]=0x%h into LED[3:0]",
                 $time, adder_b_export[3:0]);
end
// synthesis translate_on

//=======================================================
//  Write adder results into DDR3 via simple_mem
//
//  adder_a → cache line (512b all-zeros except bits[511:480]=sum_a)
//    stored at physical DDR3 address 0x3FFF_0000
//    sum_a readable at 0x3FFF_003C (last 32b of the 64-byte line)
//
//  adder_b → same layout, at 0x3FFF_0040
//    sum_b readable at 0x3FFF_007C
//=======================================================
localparam [31:0] ADDR_A = 32'h3FFF_0000;
localparam [31:0] ADDR_B = 32'h3FFF_0040;

wire [511:0] line_a = {sum_a, 480'd0};
wire [511:0] line_b = {sum_b, 480'd0};

// ── change detect ─────────────────────────────────────
reg [63:0] prev_a, prev_b;
reg        pio_dirty;
always @(posedge fpga_clk_50 or negedge hps_fpga_reset_n) begin
    if (!hps_fpga_reset_n) begin
        prev_a    <= 64'd0;
        prev_b    <= 64'd0;
        pio_dirty <= 1'b0;
    end else begin
        prev_a <= adder_a_export;
        prev_b <= adder_b_export;
        if (adder_a_export != prev_a || adder_b_export != prev_b)
            pio_dirty <= 1'b1;
        else if (seq_start)
            pio_dirty <= 1'b0;
    end
end

// synthesis translate_off
always @(posedge fpga_clk_50) begin
    if (adder_a_export != prev_a || adder_b_export != prev_b)
        $display("[PIO]  t=%0t  PIO changed → pio_dirty asserted. a=0x%016h b=0x%016h",
                 $time, adder_a_export, adder_b_export);
end
// synthesis translate_on

// ── tiny sequencer: write line_a, then line_b to DDR3 ────────────
reg  [1:0]  seq;            // 0=idle, 1=writing A, 2=writing B
reg         mem_request;
reg  [31:0] mem_addr;
reg  [511:0] mem_wdata;
wire         mem_done;
wire         seq_start = (seq == 2'd0) && pio_dirty;

// latched flag: DDR3 has been written at least once since reset
reg ddr3_written;
always @(posedge fpga_clk_50 or negedge hps_fpga_reset_n) begin
    if (!hps_fpga_reset_n) ddr3_written <= 1'b0;
    else if (mem_done)     ddr3_written <= 1'b1;
end

always @(posedge fpga_clk_50 or negedge hps_fpga_reset_n) begin
    if (!hps_fpga_reset_n) begin
        seq         <= 2'd0;
        mem_request <= 1'b0;
        mem_addr    <= 32'd0;
        mem_wdata   <= 512'd0;
    end else begin
        mem_request <= 1'b0;        // default: no request this cycle
        case (seq)
        2'd0: if (pio_dirty) begin  // kick off adder A
            mem_request <= 1'b1;
            mem_addr    <= ADDR_A;
            mem_wdata   <= line_a;
            seq         <= 2'd1;
        end
        2'd1: if (mem_done) begin   // A done → kick off B
            mem_request <= 1'b1;
            mem_addr    <= ADDR_B;
            mem_wdata   <= line_b;
            seq         <= 2'd2;
        end
        2'd2: if (mem_done) begin   // B done → back to idle
            seq <= 2'd0;
        end
        default: seq <= 2'd0;
        endcase
    end
end

// synthesis translate_off
always @(posedge fpga_clk_50) begin
    if (mem_request)
        $display("[DDR3] t=%0t  mem_request seq=%0d  addr=0x%08h  data[511:480]=0x%08h",
                 $time, seq, mem_addr, mem_wdata[511:480]);
    if (mem_done)
        $display("[DDR3] t=%0t  mem_done (DDR3 write completed)", $time);
end
// synthesis translate_on

// ── simple_mem instance (Avalon-MM writer) ────────────
wire [31:0] avm_address;
wire        avm_read;
wire        avm_write;
wire [63:0] avm_writedata;
wire [7:0]  avm_byteenable;
wire [63:0] avm_readdata;
wire        avm_readdatavalid;
wire        avm_waitrequest;

simple_mem mem0 (
    .clk            (fpga_clk_50),
    .rst_n          (hps_fpga_reset_n),
    .request        (mem_request),
    .store          (1'b1),
    .addr           (mem_addr),
    .wdata          (mem_wdata),
    .rdata          (),
    .done           (mem_done),
    .avm_address    (avm_address),
    .avm_read       (avm_read),
    .avm_write      (avm_write),
    .avm_writedata  (avm_writedata),
    .avm_byteenable (avm_byteenable),
    .avm_readdata   (avm_readdata),
    .avm_readdatavalid (avm_readdatavalid),
    .avm_waitrequest(avm_waitrequest)
);

// synthesis translate_off
always @(posedge fpga_clk_50) begin
    if (avm_write)
        $display("[AVM]  t=%0t  Avalon write addr=0x%08h data=0x%016h be=0x%02h waitreq=%b",
                 $time, avm_address, avm_writedata, avm_byteenable, avm_waitrequest);
end
// synthesis translate_on

//=======================================================
//  DEBUG word exposed via adder_sum_export[63:32]
//  Read at 0xC0000014 with:  ./devmem2 0xC0000014 w
//
//  Bit layout:
//    [31:24] = 0xDB  (magic marker — if you see this, the bridge works)
//    [23]    = heartbeat (toggles every 1 s — FPGA clock alive)
//    [22]    = hps_fpga_reset_n (1 = HPS out of reset)
//    [21]    = pio_dirty (1 = HPS just wrote a new value)
//    [20]    = ddr3_written (1 = DDR3 has been written at least once)
//    [19:18] = seq state (0=idle, 1=writing_A, 2=writing_B)
//    [17: 0] = 0 (reserved)
//=======================================================
wire [31:0] debug_word = {
    8'hDB,               // [31:24] magic marker
    heartbeat,           // [23]
    hps_fpga_reset_n,    // [22]
    pio_dirty,           // [21]
    ddr3_written,        // [20]
    seq,                 // [19:18]
    18'd0                // [17:0]
};

assign adder_sum_export = {debug_word, sum_a};

//=======================================================
//  LED assignment
//  [7]   heartbeat  — blinks ~1 Hz regardless of HPS
//  [6]   pio_dirty  — HPS wrote new data
//  [5]   seq active — DDR3 write in progress
//  [4]   hps reset  — HPS is running (active-HIGH)
//  [3:0] DEADBEEF latch — shows adder_b[3:0] after trigger
//=======================================================
assign LED = {
    heartbeat,           // [7]
    pio_dirty,           // [6]
    (seq != 2'd0),       // [5]
    hps_fpga_reset_n,    // [4]
    led_latch            // [3:0]
};

//=======================================================
//  Qsys SoC (HPS + PIOs + DDR3)
//=======================================================
soc_system u0(
               .pio128_out_new_signal   (pio128_out_export),
               .adder_a_export          (adder_a_export),
               .adder_b_export          (adder_b_export),
               .adder_sum_export        (adder_sum_export),
               .fpga_mem_address        (avm_address),
               .fpga_mem_read           (avm_read),
               .fpga_mem_readdata       (avm_readdata),
               .fpga_mem_readdatavalid  (avm_readdatavalid),
               .fpga_mem_write          (avm_write),
               .fpga_mem_writedata      (avm_writedata),
               .fpga_mem_byteenable     (avm_byteenable),
               .fpga_mem_waitrequest    (avm_waitrequest),
               .fpga_mem_burstcount     (1'b1),
               .fpga_mem_debugaccess    (1'b0),
               .clk_clk                 (FPGA_CLK1_50),
               .reset_reset_n           (hps_fpga_reset_n),
               .memory_mem_a            (HPS_DDR3_ADDR),
               .memory_mem_ba           (HPS_DDR3_BA),
               .memory_mem_ck           (HPS_DDR3_CK_P),
               .memory_mem_ck_n         (HPS_DDR3_CK_N),
               .memory_mem_cke          (HPS_DDR3_CKE),
               .memory_mem_cs_n         (HPS_DDR3_CS_N),
               .memory_mem_ras_n        (HPS_DDR3_RAS_N),
               .memory_mem_cas_n        (HPS_DDR3_CAS_N),
               .memory_mem_we_n         (HPS_DDR3_WE_N),
               .memory_mem_reset_n      (HPS_DDR3_RESET_N),
               .memory_mem_dq           (HPS_DDR3_DQ),
               .memory_mem_dqs          (HPS_DDR3_DQS_P),
               .memory_mem_dqs_n        (HPS_DDR3_DQS_N),
               .memory_mem_odt          (HPS_DDR3_ODT),
               .memory_mem_dm           (HPS_DDR3_DM),
               .memory_oct_rzqin        (HPS_DDR3_RZQ),
               .hps_0_h2f_reset_reset_n (hps_fpga_reset_n)
           );

endmodule
